#
# Test for bug 1113388: field.cc:3822: virtual longlong Field_long::val_int(): Assertion `table->in_use == _current_thd()' failed
#
--source include/have_debug_sync.inc

--source include/count_sessions.inc

CREATE TABLE t1(a INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);

SET SESSION old_alter_table=ON;

SET DEBUG_SYNC= 'after_copy_data_between_tables SIGNAL optimize_ready WAIT_FOR i_s_stopped_1';
send OPTIMIZE TABLE t1;

connect (conn2,localhost,root,,);
connection conn2;

SET DEBUG_SYNC= 'now WAIT_FOR optimize_ready';
SET DEBUG_SYNC= 'fill_global_temporary_tables_before_storing_rec SIGNAL i_s_stopped_1';
send SELECT COUNT(*) FROM INFORMATION_SCHEMA.GLOBAL_TEMPORARY_TABLES;

connection default;
reap;

connection conn2;
reap;

disconnect conn2;
connection default;

SET SESSION old_alter_table=default;
DROP TABLE t1;
SET DEBUG_SYNC= 'RESET';

--source include/wait_until_count_sessions.inc
